
public namespace const17;
import common -;

function void test1()
{
  varray{int} f;
  f.resize(10, int());
  f[3] = 99;
  slice{int} const & s = f[2..5]; // captured by const ref
  f.resize(20, int()); // would invalidate
  println(s[1]);
}

exception::set_stack_trace_limit(0);
try {
  test1();
} catch (c_exception ex) {
  println("caught", ex);
}

