caught unexpected_value{errno_t}(EINTR)

